services:
  - type: web
    name: sistema-cadastro-flask
    runtime: python
    repo: https://github.com/Luciosalomao/CursoFlask.git
    plan: free
    region: oregon
    rootDir: cadprod                   
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: SECRET_KEY
        generateValue: true